### PR TITLE
Script fixes and enhancements

### PR DESCRIPTION
**Pull request by ekrekeler**
I made multiple modifications to scripts where errors existed, and added a few enhancements as well.
I figured one pull request would be easier, but please let me know if/how you would like these separated.

### CODE REVIEW

**Comment by ekrekeler** [comment]
Forgot to mention, I did test building and deploying this with two existing pihole containers in docker and had no issues.

**Comment by nh-mike** [comment]
Thanks, @ekrekeler
Unfortunately I hadn't seen either the issue raised, nor the pull request until now as I have been away, however I'll review in the next day or two and come back if I have any questions.

Cheers.

**Comment by nh-mike** [comment]
Again, thanks @ekrekeler I have reviewed all the changes and I am happy with all of them. I am surprised how many mistakes I've made that you've picked up on so have a cookie! :cookie:

As yet, I haven't built testing the prelaunch into my testing workflow, however it is definitely on the horizon. Much appreciation for your assistance on this.

**Comment by ekrekeler** [comment]
Hey @nh-mike ,
Thanks for merging, and for the cookie. :)

I should let you know this is a great collection of scripts you had already, otherwise I wouldn't have bothered contributing. I was upset to find that gravity-sync doesn't support running in a docker container natively, but glad you had already figured out a way to make it work. Hopefully this will be included in gravity-sync itself someday.

Keep up the good work!

**Pull request merged**
